Traceback (most recent call last):
  File "/Users/michielnoback/opt/miniconda3/envs/education/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/michielnoback/opt/miniconda3/envs/education/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/michielnoback/opt/miniconda3/envs/education/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/michielnoback/opt/miniconda3/envs/education/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/michielnoback/opt/miniconda3/envs/education/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/michielnoback/opt/miniconda3/envs/education/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/michielnoback/opt/miniconda3/envs/education/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/michielnoback/opt/miniconda3/envs/education/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
def process_data(data):
    print("processing data")
    for e in data:
        process_person(e)

def process_person(tup):
    print("processing person")
    print(f"last name={tup[1]}")

my_data = [("Mike", "Mutter"), ("Ralph Racker", ), ("Louis", "Levee")]
process_data(my_data)

------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mIndexError[0m                                Traceback (most recent call last)
Cell [0;32mIn[1], line 11[0m
[1;32m      8[0m     [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mlast name=[39m[38;5;132;01m{[39;00mtup[[38;5;241m1[39m][38;5;132;01m}[39;00m[38;5;124m"[39m)
[1;32m     10[0m my_data [38;5;241m=[39m [([38;5;124m"[39m[38;5;124mMike[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mMutter[39m[38;5;124m"[39m), ([38;5;124m"[39m[38;5;124mRalph Racker[39m[38;5;124m"[39m, ), ([38;5;124m"[39m[38;5;124mLouis[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mLevee[39m[38;5;124m"[39m)]
[0;32m---> 11[0m [43mprocess_data[49m[43m([49m[43mmy_data[49m[43m)[49m

Cell [0;32mIn[1], line 4[0m, in [0;36mprocess_data[0;34m(data)[0m
[1;32m      2[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mprocessing data[39m[38;5;124m"[39m)
[1;32m      3[0m [38;5;28;01mfor[39;00m e [38;5;129;01min[39;00m data:
[0;32m----> 4[0m     [43mprocess_person[49m[43m([49m[43me[49m[43m)[49m

Cell [0;32mIn[1], line 8[0m, in [0;36mprocess_person[0;34m(tup)[0m
[1;32m      6[0m [38;5;28;01mdef[39;00m [38;5;21mprocess_person[39m(tup):
[1;32m      7[0m     [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mprocessing person[39m[38;5;124m"[39m)
[0;32m----> 8[0m     [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mlast name=[39m[38;5;132;01m{[39;00m[43mtup[49m[43m[[49m[38;5;241;43m1[39;49m[43m][49m[38;5;132;01m}[39;00m[38;5;124m"[39m)

[0;31mIndexError[0m: tuple index out of range
IndexError: tuple index out of range

